repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: [pytest, click]
  - repo: local
    hooks:
      - id: tests-and-badges
        name: Run tests and update badges
        entry: python3 scripts/update_badges.py
        language: system
        pass_filenames: false
        always_run: true
