"""Constants for gemma-4-sql."""

DEFAULT_PRETRAIN_DATASET = "my-custom-dataset"
DEFAULT_SFT_DATASET = "my-custom-sft-dataset"
DEFAULT_POSTTRAIN_DATASET = "my-custom-dpo-dataset"
MODEL_GEMMA4_E2B = "google/gemma-4-E2B"
MODEL_GEMMA4_E2B_IT = "google/gemma-4-E2B-it"
MODEL_GEMMA4_E4B = "google/gemma-4-E4B"
MODEL_GEMMA4_E4B_IT = "google/gemma-4-E4B-it"
MODEL_GEMMA4_26B_A4B = "google/gemma-4-26B-A4B"
MODEL_GEMMA4_26B_A4B_IT = "google/gemma-4-26B-A4B-it"
MODEL_GEMMA4_31B = "google/gemma-4-31B"
MODEL_GEMMA4_31B_IT = "google/gemma-4-31B-it"
